### ISSUE TITLE
При пустому переліку Групування кнопка +Створити активна, але нічого не робить

### ISSUE THREAD

**Issue by AndriyNesterenya** [nova-era-ua/Nova.Era#19]
При пустому переліку Групування кнопка +Створити активна, але нічого не робить - треба клікати на "дзьобик" праворуч від кнопки, що неочевидно

**Comment by AndriyNesterenya** [comment]
І взагалі з нинішньою подвійною кнопкою навігація незручна і незрозуміла. 
Потрібен більш логічний спосіб вийти з підгрупи, створити нову підгрупу і т.д.

**Comment by alex-kukhtin** [comment]
Давай обсудим. Если есть идеи - я готов.
